services:
  postgres_db:
    image: postgres:17.4-alpine
    container_name: postgres_db
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./backend/.env
    
  backend:
    build: ./backend
    command: gunicorn book_store.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 1000

    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    env_file:
      - ./backend/.env
    
  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    container_name: celery_worker
    command: sh -c "celery -A book_store worker -l info & celery -A book_store beat -l info"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend

  frontend:
    build: ./frontend
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
      
volumes:
  postgres_data: