# Generated by Django 6.0.1 on 2026-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_category'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(related_name='books', to='core.language'),
        ),
    ]
