# Generated by Django 6.0.1 on 2026-02-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
