# Generated by Django 6.0.1 on 2026-02-18 10:43

import django.db.models.deletion
import utils.book
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=utils.book.book_image_directory_path)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
