# Generated by Django 6.0.1 on 2026-02-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_bookimage_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookimage',
            old_name='image',
            new_name='image_file',
        ),
    ]
