# Generated by Django 6.0.1 on 2026-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='num_of_pages',
            field=models.PositiveSmallIntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='num_of_ratings',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
