# Generated by Django 6.0.1 on 2026-02-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_book_description_book_num_of_pages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='review_stars',
            new_name='average_rating',
        ),
    ]
