# Generated by Django 6.0.1 on 2026-02-25 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_rename_review_stars_book_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='stars',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
