# Generated by Django 6.0.1 on 2026-03-12 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_booksale'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksale',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_sale', to='order.userorder'),
        ),
    ]
