# Generated by Django 6.0.1 on 2026-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('editor', 'editor'), ('viewer', 'viewer')], default='viewer', max_length=10),
        ),
    ]
