# Generated by Django 6.0.1 on 2026-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'superuser'), ('admin', 'admin'), ('editor', 'editor'), ('viewer', 'viewer')], default='viewer', max_length=10),
        ),
    ]
