# Generated by Django 6.0.1 on 2026-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_userlogintrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogintrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlogintrack',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlogintrack',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userlogintrack',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
