# Generated by Django 6.0.1 on 2026-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_alter_userlogintrack_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogintrack',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userlogintrack',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
