# Generated by Django 6.0.1 on 2026-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_userlogintrack_city_userlogintrack_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogintrack',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
