# Generated by Django 6.0.1 on 2026-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_alter_userlogintrack_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogintrack',
            name='user_agent',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
