# Generated by Django 6.0.1 on 2026-03-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='street_address',
            new_name='street',
        ),
    ]
