# Generated by Django 6.0.1 on 2026-03-12 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_rename_street_address_useraddress_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 17, 4, 10, 0, 474770, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
