# Generated by Django 6.0.1 on 2026-03-12 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0018_userorder_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 17, 4, 10, 5, 782701, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
