# Generated by Django 6.0.1 on 2026-03-12 04:11

import utils.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0019_alter_userorder_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='estimated_delivery_date',
            field=models.DateField(default=utils.sale.default_delivery_date, null=True),
        ),
    ]
