# Generated by Django 6.0.1 on 2026-03-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_booksale_order'),
        ('useraccount', '0020_alter_userorder_estimated_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='delivery_person',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userlogintrack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserLoginTrack',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
