# Generated by Django 6.0.1 on 2026-03-12 04:29

import django.core.validators
import django.db.models.deletion
import utils.sale
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9779899888888, and upt to 15 digits allowed', regex='^\\+?\\d{7,15}$')])),
                ('alt_phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9779899888888, and upt to 15 digits allowed', regex='^\\+?\\d{7,15}$')])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.PositiveSmallIntegerField(choices=[(0, 'Home'), (1, 'Office'), (2, 'Other')], default=0)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9779899888888, and upt to 15 digits allowed', regex='^\\+?\\d{7,15}$')])),
                ('alt_phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9779899888888, and upt to 15 digits allowed', regex='^\\+?\\d{7,15}$')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=700, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_track', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'ordered'), (2, 'processing'), (3, 'shipped'), (4, 'delivered'), (5, 'cancelled'), (6, 'returned'), (7, 'refunded')], default=0)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (2, 'paid'), (3, 'failed'), (4, 'refunded')], default=0)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('expected_delivery_date', models.DateField(default=utils.sale.default_delivery_date, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.useraddress')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='order.deliveryperson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
