# Generated by Django 6.0.1 on 2026-03-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginTrack',
        ),
    ]
