name: Python package

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python manage.py test
   