name: Python package

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend

      - name: Run Tests
        env:
          USE_SQLITE: "True"
        run: |
          celery -A book_store worker -l info & celery -A book_store beat -l info
          python manage.py test
        working-directory: ./backend
   